### PR TITLE
Merge wasmlink into witx-bindgen.

### PR DESCRIPTION
**Pull request by peterhuene**

### CODE REVIEW

**Comment by peterhuene** [comment]
It looks like witx-bindgen isn't working on Windows, but I haven't looked into it yet.

I'm also getting other wasmlink test failures that I'm investigating.

**Review by alexcrichton — APPROVED** [review]
Looks good to me! I think there's some CI issues though?

I'll also add you to the repo so you can merge too

**Comment by peterhuene** [comment]
I figured out the issue: the proc-macros that are doing a `include_str!` aren't accounting for the path separator difference on Windows, hence the "unknown escape character" issue.

Fix is to use a raw-string literal for the proc-macro output.  I'll push up a fix.

**Comment by peterhuene** [comment]
Additional failures in es-lint test that are probably the same thing, fixing that now.

**Comment by alexcrichton** [comment]
Oh oops I didn't realize these were failures in preexisting code just now cropping up on Windows since I didn't test there before.

Feel free to comment out windows for now and I can get to fixing these later too

**Pull request merged**
